#!/usr/bin/env node

/**
 * YouTube Enrichment Script (yt-dlp powered)
 *
 * Reads chart JSON files from data/charts/ and enriches them
 * with embeddable YouTube video IDs for in-app playback.
 *
 * Prefers YouTube Music "Topic" channel versions which are
 * universally embeddable (no domain restrictions). Falls back
 * to official uploads filtered by playable_in_embed.
 *
 * Prerequisites:
 *   brew install yt-dlp
 *
 * Usage:
 *   node scripts/enrich-youtube.mjs
 *   node scripts/enrich-youtube.mjs --country us
 *   node scripts/enrich-youtube.mjs --country us --year 1990
 */

import fs from "fs";
import path from "path";
import { execFile } from "child_process";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = path.join(__dirname, "..");
const DATA_DIR = path.join(ROOT_DIR, "data", "charts");

// Parse flags
const args = process.argv.slice(2);
function getFlag(name) {
  const idx = args.indexOf(`--${name}`);
  return idx !== -1 && args[idx + 1] ? args[idx + 1] : null;
}

const countryFlag = getFlag("country");
const yearFlag = getFlag("year");

/**
 * Search YouTube and return the first result matching the filter.
 * Uses ytsearch5 for multiple candidates.
 */
function ytSearch(query, matchFilter) {
  const ytArgs = [
    `ytsearch5:${query}`,
    "--get-id",
    "--no-warnings",
  ];
  if (matchFilter) {
    ytArgs.push("--match-filter", matchFilter);
  }
  return new Promise((resolve) => {
    execFile("yt-dlp", ytArgs, { timeout: 30000 }, (err, stdout) => {
      if (err) {
        resolve(null);
        return;
      }
      const ids = stdout.trim().split("\n").filter(Boolean);
      resolve(ids[0] || null);
    });
  });
}

/**
 * Get video metadata to check channel type.
 * Returns { id, channel, channelUrl, playableInEmbed } or null.
 */
function getVideoInfo(videoId) {
  return new Promise((resolve) => {
    execFile(
      "yt-dlp",
      [
        `https://www.youtube.com/watch?v=${videoId}`,
        "--dump-json",
        "--no-warnings",
        "--skip-download",
      ],
      { timeout: 15000 },
      (err, stdout) => {
        if (err) { resolve(null); return; }
        try {
          const d = JSON.parse(stdout);
          resolve({
            id: d.id,
            channel: d.channel,
            channelUrl: d.channel_url || "",
            playableInEmbed: d.playable_in_embed === true,
            description: (d.description || "").toLowerCase(),
          });
        } catch {
          resolve(null);
        }
      }
    );
  });
}

/**
 * Check if a video is from a YouTube Music Topic channel.
 * Topic channels have auto-generated content that is universally embeddable.
 */
function isTopicChannel(info) {
  if (!info) return false;
  return info.description.includes("provided to youtube") ||
         info.description.includes("auto-generated by youtube");
}

async function searchYouTube(title, artist) {
  // Strategy 1: Find a Topic channel version (universally embeddable)
  // Topic channel videos have plain titles like "Song Name" by "Artist - Topic"
  const topicQuery = `${artist} ${title} auto-generated provided to youtube`;
  const topicId = await ytSearch(topicQuery, "playable_in_embed");
  if (topicId) {
    const info = await getVideoInfo(topicId);
    if (info && isTopicChannel(info)) {
      return topicId;
    }
  }

  // Strategy 2: Search with title + artist (often returns Topic results)
  const simpleId = await ytSearch(`${title} ${artist}`, "playable_in_embed");
  if (simpleId) {
    const info = await getVideoInfo(simpleId);
    if (info && isTopicChannel(info)) {
      return simpleId;
    }
    // Keep as fallback if no Topic version found
    var fallbackId = simpleId;
  }

  // Strategy 3: Official version (may have domain restrictions but works on real domains)
  const officialId = await ytSearch(`${artist} ${title} official`, "playable_in_embed");
  if (officialId) {
    const info = await getVideoInfo(officialId);
    if (info && isTopicChannel(info)) {
      return officialId;
    }
    // Prefer this over the simple search fallback
    if (!fallbackId) fallbackId = officialId;
  }

  // Strategy 4: Audio version
  const audioId = await ytSearch(`${artist} ${title} audio`, "playable_in_embed");
  if (audioId) {
    const info = await getVideoInfo(audioId);
    if (info && isTopicChannel(info)) {
      return audioId;
    }
    if (!fallbackId) fallbackId = audioId;
  }

  // Return best non-Topic fallback (will work on deployed domains, may fail on localhost)
  return fallbackId || null;
}

async function main() {
  // Verify yt-dlp is installed
  const testId = await ytSearch("never gonna give you up rick astley", "playable_in_embed");
  if (!testId) {
    console.error("yt-dlp not found or not working. Install with: brew install yt-dlp");
    process.exit(1);
  }
  console.log("YouTube Enrichment Script (yt-dlp)");
  console.log("=".repeat(40));
  console.log("Prefers Topic channel versions (universally embeddable)\n");

  const countries = fs.readdirSync(DATA_DIR).filter((f) => {
    if (!fs.statSync(path.join(DATA_DIR, f)).isDirectory()) return false;
    if (countryFlag) return f === countryFlag;
    return true;
  });

  if (countries.length === 0) {
    console.error(
      countryFlag
        ? `No chart directory found for country: ${countryFlag}`
        : "No chart directories found"
    );
    process.exit(1);
  }

  let totalTracks = 0;
  let enrichedTracks = 0;
  let topicTracks = 0;
  let skippedTracks = 0;
  let failedTracks = 0;
  let totalFiles = 0;

  for (const country of countries) {
    const dir = path.join(DATA_DIR, country);
    let files = fs.readdirSync(dir).filter((f) => f.endsWith(".json"));

    if (yearFlag) {
      files = files.filter((f) => f === `${yearFlag}.json`);
      if (files.length === 0) {
        console.log(`No chart file for ${country}/${yearFlag}.json, skipping.`);
        continue;
      }
    }

    for (const file of files) {
      const filePath = path.join(dir, file);
      const chart = JSON.parse(fs.readFileSync(filePath, "utf-8"));
      totalFiles++;
      console.log(
        `\n[${totalFiles}] ${country}/${file} (${chart.tracks.length} tracks)`
      );

      let modified = false;
      for (const track of chart.tracks) {
        totalTracks++;

        if (track.youtubeId) {
          skippedTracks++;
          console.log(
            `  ${track.rank}. ${track.title} — ${track.artist} [skipped]`
          );
          continue;
        }

        console.log(`  ${track.rank}. ${track.title} — ${track.artist}`);
        const videoId = await searchYouTube(track.title, track.artist);

        if (videoId) {
          track.youtubeId = videoId;
          enrichedTracks++;
          modified = true;
          // Check if it's a Topic version
          const info = await getVideoInfo(videoId);
          const isTopic = isTopicChannel(info);
          if (isTopic) topicTracks++;
          console.log(`    ✓ ${videoId}${isTopic ? " [Topic]" : ""}`);
        } else {
          failedTracks++;
          console.log(`    ✗ Not found`);
        }

        await new Promise((r) => setTimeout(r, 300));
      }

      if (modified) {
        fs.writeFileSync(filePath, JSON.stringify(chart, null, 2) + "\n");
      }
    }
  }

  console.log(`\n${"=".repeat(40)}`);
  console.log(`Done! Results:`);
  console.log(`  Files processed: ${totalFiles}`);
  console.log(`  Total tracks:    ${totalTracks}`);
  console.log(`  Enriched:        ${enrichedTracks}`);
  console.log(`    Topic channel: ${topicTracks}`);
  console.log(`    Other:         ${enrichedTracks - topicTracks}`);
  console.log(`  Skipped:         ${skippedTracks}`);
  console.log(`  Not found:       ${failedTracks}`);
}

main().catch(console.error);
